name: macos-ci

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  # cancel jobs on PRs only
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: MacOS CI Tests
    runs-on: [macos-14]
    defaults:
      run:
        working-directory: platform/ios
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Setup Bazel
        run: cp platform/macos/bazel/example_config.bzl platform/macos/config.bzl
      
      - name: Build app for macOS
        run: bazel build //platform/macos/app:macos_app --//:renderer=metal
      